name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vault CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y vault jq

      - name: Authenticate with Vault
        env:
          VAULT_ADDR: https://vault.example.com
          ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id=$ROLE_ID secret_id=$SECRET_ID)
          echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV

      - name: Fetch GitHub credentials from Vault
        run: |
          GITHUB_USER=$(vault kv get -field=username secret/github --token=$VAULT_TOKEN)
          GITHUB_TOKEN=$(vault kv get -field=token secret/github --token=$VAULT_TOKEN)
          echo "GITHUB_USER=$GITHUB_USER" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

      - name: Build & Test
        run: |
          npm ci
          npm test

      - name: Docker Build & Push
        run: |
          DOCKER_USER=$(vault kv get -field=username secret/dockerhub --token=$VAULT_TOKEN)
          DOCKER_PASS=$(vault kv get -field=password secret/dockerhub --token=$VAULT_TOKEN)
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          IMAGE_NAME="myrepo/myimage"
          IMAGE_TAG="${TIMESTAMP}-build${GITHUB_RUN_NUMBER}"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
